/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company;

import com.company.asset.Difficulty;
import java.awt.Color;

/**
 *
 * @author ville
 */
public class SettingsPanel extends javax.swing.JPanel {

    
    
    private Frame frame;
    
    private final Color ON = new Color(140, 255, 90);
    private final Color OFF = new Color(255, 100, 100);
    private final Color WRITE = new Color(145, 180, 230);
    private final Color NOTE = new Color(195, 215, 250);
    
    public SettingsPanel() {
        initComponents();
        
        init();
    }
    
    public void setFrame(Frame frame) {
        this.frame = frame;
    }
    
    
    public void init() {
        btnToggleHint.setBackground(OFF);
        btnToggleHighlights.setSelected(true);
        btnToggleHighlights.setBackground(ON);
        btnToggleMode.setSelected(true);
        btnToggleMode.setBackground(WRITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panelSettings = new javax.swing.JPanel();
        btnToggleHighlights = new javax.swing.JToggleButton();
        btnToggleHint = new javax.swing.JToggleButton();
        btnToggleMode = new javax.swing.JToggleButton();
        lblMode = new javax.swing.JLabel();
        lblHints = new javax.swing.JLabel();
        lblHighlights = new javax.swing.JLabel();
        panelActions = new javax.swing.JPanel();
        sliderDifficulty = new javax.swing.JSlider();
        btnGenerate = new javax.swing.JButton();
        btnSolve = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblGenerationTime = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Difficulty", "Time"
            }
        ));
        jScrollPane1.setViewportView(table);

        panelSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 12))); // NOI18N
        panelSettings.setToolTipText("");
        panelSettings.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        btnToggleHighlights.setText("ON");
        btnToggleHighlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleHighlightsActionPerformed(evt);
            }
        });

        btnToggleHint.setText("OFF");
        btnToggleHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleHintActionPerformed(evt);
            }
        });

        btnToggleMode.setText("WRITE");
        btnToggleMode.setMaximumSize(new java.awt.Dimension(60, 32));
        btnToggleMode.setMinimumSize(new java.awt.Dimension(60, 32));
        btnToggleMode.setPreferredSize(new java.awt.Dimension(60, 32));
        btnToggleMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToggleModeMouseClicked(evt);
            }
        });

        lblMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMode.setText("Mode");

        lblHints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHints.setText("Hints");

        lblHighlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighlights.setText("Highlights");

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSettingsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnToggleMode, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(lblMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnToggleHint, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(lblHints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHighlights, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnToggleHighlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMode)
                    .addComponent(lblHints)
                    .addComponent(lblHighlights))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnToggleHint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToggleHighlights, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToggleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelActions.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Actions\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 12))); // NOI18N

        sliderDifficulty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDifficultyStateChanged(evt);
            }
        });

        btnGenerate.setText("New Sudoku");
        btnGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateMouseClicked(evt);
            }
        });

        btnSolve.setText("Solve");
        btnSolve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolveMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(sliderDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionsLayout.createSequentialGroup()
                        .addComponent(btnGenerate)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionsLayout.createSequentialGroup()
                        .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear)
                            .addComponent(btnSolve))
                        .addGap(54, 54, 54))))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sliderDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerate)
                .addGap(44, 44, 44)
                .addComponent(btnSolve)
                .addGap(46, 46, 46)
                .addComponent(btnClear)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblGenerationTime.setText("Generated a new Sudoku with difficulty [DIFFICULTY] in [MILLISECONDS] ms.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblGenerationTime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(panelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblGenerationTime)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnToggleHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleHintActionPerformed
        // TODO add your handling code here:
        frame.getGamePanel().setHints(btnToggleHint.isSelected());
                
        if (btnToggleHint.isSelected()) {
            btnToggleHint.setText("ON");
            btnToggleHint.setBackground(ON);
        } else {
            btnToggleHint.setText("OFF");
            btnToggleHint.setBackground(OFF);
        }
    }//GEN-LAST:event_btnToggleHintActionPerformed

    private void btnToggleHighlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleHighlightsActionPerformed
        // TODO add your handling code here:
        frame.getGamePanel().setHightlights(btnToggleHighlights.isSelected());
                
        if (btnToggleHighlights.isSelected()) {
            btnToggleHighlights.setText("ON");
            btnToggleHighlights.setBackground(ON);
        } else {
            btnToggleHighlights.setText("OFF");
            btnToggleHighlights.setBackground(OFF);
        }
    }//GEN-LAST:event_btnToggleHighlightsActionPerformed

    private void btnToggleModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToggleModeMouseClicked
        // TODO add your handling code here:
        frame.getGamePanel().setMode(btnToggleMode.isSelected());
                
        if (btnToggleMode.isSelected()) {
            btnToggleMode.setText("WRITE");
            btnToggleMode.setBackground(WRITE);
        } else {
            btnToggleMode.setText("NOTE");
            btnToggleMode.setBackground(NOTE);
        }
    }//GEN-LAST:event_btnToggleModeMouseClicked

    private void btnGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateMouseClicked
        // TODO add your handling code here:
        frame.getGamePanel().generateNewGrid(Difficulty.MEDIUM);
    }//GEN-LAST:event_btnGenerateMouseClicked

    private void btnSolveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolveMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseClicked

    private void sliderDifficultyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDifficultyStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderDifficultyStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSolve;
    private javax.swing.JToggleButton btnToggleHighlights;
    private javax.swing.JToggleButton btnToggleHint;
    private javax.swing.JToggleButton btnToggleMode;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGenerationTime;
    private javax.swing.JLabel lblHighlights;
    private javax.swing.JLabel lblHints;
    private javax.swing.JLabel lblMode;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JSlider sliderDifficulty;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
